import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Speedy Rentals</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About Speedy Rentals</h1>
      <p>
        {' '}
        Speedy Rentals is the UK's largest car sharing marketplace where you can book any car you want, wherever you want it, from a vibrant community of trusted hosts across the globe.
        Whether you're flying in from afar or looking for a car down the street, searching for a rugged truck or something smooth and swanky, guests can take the wheel of the perfect
        car for any occasion, while hosts can take the wheel of their futures by building an accessible, flexible, and scalable car sharing business from the ground up.
      </p>
    </div>
  )
}