
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import styless from '../styles/Buttons.module.css'
import Navbar from '../components/Navbar'
import React, {useState} from 'react'


export default function Login() {
  const [inputValue, setInputValue]=useState('')
  return (
    <div className={styles.container}>
      <Head>
        <title>Log in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Login Page </h1>
      <label>
      {' '}
        Username:
        {' '}
        <input type="text" value={inputValue} onChange={event =>
        setInputValue(event.target.value)} />
      </label>

      <label1>
      {' '}
        Password:
        {' '}
        <input type="text" value={inputValue} onChange={event =>
        setInputValue(event.target.value)} />
        <button className={styless.customButton}>Log in</button>
      </label1>

    </div>
  )
}
